export {
  BrandDescription,
  BrandEyebrow,
  BrandMark,
  BrandTitle,
  FieldGroup,
  FieldLabel,
  FormFooter,
  FormSubtitle,
  FormTitle,
  PasswordField,
  SignInCard as SignUpCard,
  SignInPageWrapper as SignUpPageWrapper,
  WrapperContainerLeft,
  WrapperContainerRight,
  WrapperTextLight,
} from "../SignInPage/style";
